server:
  port: 5000
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/bbscloud
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
# eureka address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
